In [18]:
import numpy as np

In [19]:
alphabets='ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [20]:
len(alphabets)

26

In [21]:
int_to_char=dict((i,v) for i,v in enumerate(alphabets))
int_to_char

{0: 'A',
 1: 'B',
 2: 'C',
 3: 'D',
 4: 'E',
 5: 'F',
 6: 'G',
 7: 'H',
 8: 'I',
 9: 'J',
 10: 'K',
 11: 'L',
 12: 'M',
 13: 'N',
 14: 'O',
 15: 'P',
 16: 'Q',
 17: 'R',
 18: 'S',
 19: 'T',
 20: 'U',
 21: 'V',
 22: 'W',
 23: 'X',
 24: 'Y',
 25: 'Z'}

In [22]:
char_to_int=dict((v,i) for i,v in enumerate(alphabets))

In [23]:
char_to_int

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'J': 9,
 'K': 10,
 'L': 11,
 'M': 12,
 'N': 13,
 'O': 14,
 'P': 15,
 'Q': 16,
 'R': 17,
 'S': 18,
 'T': 19,
 'U': 20,
 'V': 21,
 'W': 22,
 'X': 23,
 'Y': 24,
 'Z': 25}

In [27]:
char_to_int['A']

0

In [30]:
x=[]
y=[]
seq_length=3
for i in range(len(alphabets)-seq_length):
    seq_in=alphabets[i:i+seq_length]
    seq_out=alphabets[i+seq_length]
    x.append([char_to_int[char1] for char1 in seq_in])
    y.append(char_to_int[seq_out])
    print(seq_in,'->',seq_out)
    


ABC -> D
BCD -> E
CDE -> F
DEF -> G
EFG -> H
FGH -> I
GHI -> J
HIJ -> K
IJK -> L
JKL -> M
KLM -> N
LMN -> O
MNO -> P
NOP -> Q
OPQ -> R
PQR -> S
QRS -> T
RST -> U
STU -> V
TUV -> W
UVW -> X
VWX -> Y
WXY -> Z


In [32]:
x

[[0, 1, 2],
 [1, 2, 3],
 [2, 3, 4],
 [3, 4, 5],
 [4, 5, 6],
 [5, 6, 7],
 [6, 7, 8],
 [7, 8, 9],
 [8, 9, 10],
 [9, 10, 11],
 [10, 11, 12],
 [11, 12, 13],
 [12, 13, 14],
 [13, 14, 15],
 [14, 15, 16],
 [15, 16, 17],
 [16, 17, 18],
 [17, 18, 19],
 [18, 19, 20],
 [19, 20, 21],
 [20, 21, 22],
 [21, 22, 23],
 [22, 23, 24]]

In [33]:
y

[3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25]

In [34]:
from tensorflow.keras.utils import to_categorical

In [35]:
y_new=to_categorical(y)

In [36]:
y_new

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

In [37]:
y_new.shape

(23, 26)

In [38]:
import numpy as np

In [39]:
np.array(x).shape

(23, 3)

In [40]:
x.shape

AttributeError: 'list' object has no attribute 'shape'

In [41]:
x=np.reshape(x,(23,3,1))

In [42]:
x

array([[[ 0],
        [ 1],
        [ 2]],

       [[ 1],
        [ 2],
        [ 3]],

       [[ 2],
        [ 3],
        [ 4]],

       [[ 3],
        [ 4],
        [ 5]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 5],
        [ 6],
        [ 7]],

       [[ 6],
        [ 7],
        [ 8]],

       [[ 7],
        [ 8],
        [ 9]],

       [[ 8],
        [ 9],
        [10]],

       [[ 9],
        [10],
        [11]],

       [[10],
        [11],
        [12]],

       [[11],
        [12],
        [13]],

       [[12],
        [13],
        [14]],

       [[13],
        [14],
        [15]],

       [[14],
        [15],
        [16]],

       [[15],
        [16],
        [17]],

       [[16],
        [17],
        [18]],

       [[17],
        [18],
        [19]],

       [[18],
        [19],
        [20]],

       [[19],
        [20],
        [21]],

       [[20],
        [21],
        [22]],

       [[21],
        [22],
        [23]],

       [[22],
        [23],
    

In [45]:
#normalize 
x=x/25

In [46]:
x

array([[[0.        ],
        [0.00015686],
        [0.00031373]],

       [[0.00015686],
        [0.00031373],
        [0.00047059]],

       [[0.00031373],
        [0.00047059],
        [0.00062745]],

       [[0.00047059],
        [0.00062745],
        [0.00078431]],

       [[0.00062745],
        [0.00078431],
        [0.00094118]],

       [[0.00078431],
        [0.00094118],
        [0.00109804]],

       [[0.00094118],
        [0.00109804],
        [0.0012549 ]],

       [[0.00109804],
        [0.0012549 ],
        [0.00141176]],

       [[0.0012549 ],
        [0.00141176],
        [0.00156863]],

       [[0.00141176],
        [0.00156863],
        [0.00172549]],

       [[0.00156863],
        [0.00172549],
        [0.00188235]],

       [[0.00172549],
        [0.00188235],
        [0.00203922]],

       [[0.00188235],
        [0.00203922],
        [0.00219608]],

       [[0.00203922],
        [0.00219608],
        [0.00235294]],

       [[0.00219608],
        [0.00235294],
    

In [47]:
import tensorflow as tf

In [48]:
# Build model
model=tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(25,activation='relu'))
model.add(tf.keras.layers.LSTM(128))
model.add(tf.keras.layers.Dense(26,activation='softmax'))

In [ ]:
model