In [1]:
import numpy as np

In [2]:
alphabets='ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [3]:
len(alphabets)

26

In [4]:
int_to_char=dict((i,v) for i,v in enumerate(alphabets))
int_to_char

{0: 'A',
 1: 'B',
 2: 'C',
 3: 'D',
 4: 'E',
 5: 'F',
 6: 'G',
 7: 'H',
 8: 'I',
 9: 'J',
 10: 'K',
 11: 'L',
 12: 'M',
 13: 'N',
 14: 'O',
 15: 'P',
 16: 'Q',
 17: 'R',
 18: 'S',
 19: 'T',
 20: 'U',
 21: 'V',
 22: 'W',
 23: 'X',
 24: 'Y',
 25: 'Z'}

In [5]:
char_to_int=dict((v,i) for i,v in enumerate(alphabets))

In [6]:
char_to_int

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'J': 9,
 'K': 10,
 'L': 11,
 'M': 12,
 'N': 13,
 'O': 14,
 'P': 15,
 'Q': 16,
 'R': 17,
 'S': 18,
 'T': 19,
 'U': 20,
 'V': 21,
 'W': 22,
 'X': 23,
 'Y': 24,
 'Z': 25}

In [7]:
char_to_int['A']

0

In [8]:
x=[]
y=[]
seq_length=3
for i in range(len(alphabets)-seq_length):
    seq_in=alphabets[i:i+seq_length]
    seq_out=alphabets[i+seq_length]
    x.append([char_to_int[char1] for char1 in seq_in])
    y.append(char_to_int[seq_out])
    print(seq_in,'->',seq_out)
    


ABC -> D
BCD -> E
CDE -> F
DEF -> G
EFG -> H
FGH -> I
GHI -> J
HIJ -> K
IJK -> L
JKL -> M
KLM -> N
LMN -> O
MNO -> P
NOP -> Q
OPQ -> R
PQR -> S
QRS -> T
RST -> U
STU -> V
TUV -> W
UVW -> X
VWX -> Y
WXY -> Z


In [9]:
x

[[0, 1, 2],
 [1, 2, 3],
 [2, 3, 4],
 [3, 4, 5],
 [4, 5, 6],
 [5, 6, 7],
 [6, 7, 8],
 [7, 8, 9],
 [8, 9, 10],
 [9, 10, 11],
 [10, 11, 12],
 [11, 12, 13],
 [12, 13, 14],
 [13, 14, 15],
 [14, 15, 16],
 [15, 16, 17],
 [16, 17, 18],
 [17, 18, 19],
 [18, 19, 20],
 [19, 20, 21],
 [20, 21, 22],
 [21, 22, 23],
 [22, 23, 24]]

In [10]:
y

[3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25]

In [11]:
from tensorflow.keras.utils import to_categorical

In [12]:
y_new=to_categorical(y)

In [13]:
y_new

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

In [14]:
y_new.shape

(23, 26)

In [15]:
import numpy as np

In [16]:
np.array(x).shape

(23, 3)

In [17]:
x=np.reshape(x,(23,3,1))

In [18]:
x

array([[[ 0],
        [ 1],
        [ 2]],

       [[ 1],
        [ 2],
        [ 3]],

       [[ 2],
        [ 3],
        [ 4]],

       [[ 3],
        [ 4],
        [ 5]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 5],
        [ 6],
        [ 7]],

       [[ 6],
        [ 7],
        [ 8]],

       [[ 7],
        [ 8],
        [ 9]],

       [[ 8],
        [ 9],
        [10]],

       [[ 9],
        [10],
        [11]],

       [[10],
        [11],
        [12]],

       [[11],
        [12],
        [13]],

       [[12],
        [13],
        [14]],

       [[13],
        [14],
        [15]],

       [[14],
        [15],
        [16]],

       [[15],
        [16],
        [17]],

       [[16],
        [17],
        [18]],

       [[17],
        [18],
        [19]],

       [[18],
        [19],
        [20]],

       [[19],
        [20],
        [21]],

       [[20],
        [21],
        [22]],

       [[21],
        [22],
        [23]],

       [[22],
        [23],
    

In [19]:
#normalize 
x=x/25

In [20]:
x

array([[[0.  ],
        [0.04],
        [0.08]],

       [[0.04],
        [0.08],
        [0.12]],

       [[0.08],
        [0.12],
        [0.16]],

       [[0.12],
        [0.16],
        [0.2 ]],

       [[0.16],
        [0.2 ],
        [0.24]],

       [[0.2 ],
        [0.24],
        [0.28]],

       [[0.24],
        [0.28],
        [0.32]],

       [[0.28],
        [0.32],
        [0.36]],

       [[0.32],
        [0.36],
        [0.4 ]],

       [[0.36],
        [0.4 ],
        [0.44]],

       [[0.4 ],
        [0.44],
        [0.48]],

       [[0.44],
        [0.48],
        [0.52]],

       [[0.48],
        [0.52],
        [0.56]],

       [[0.52],
        [0.56],
        [0.6 ]],

       [[0.56],
        [0.6 ],
        [0.64]],

       [[0.6 ],
        [0.64],
        [0.68]],

       [[0.64],
        [0.68],
        [0.72]],

       [[0.68],
        [0.72],
        [0.76]],

       [[0.72],
        [0.76],
        [0.8 ]],

       [[0.76],
        [0.8 ],
        [0.84]],



In [21]:
import tensorflow as tf

In [22]:
# Build model
model=tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(25,input_shape=(3,1),activation='relu'))
model.add(tf.keras.layers.LSTM(128))
model.add(tf.keras.layers.Dense(26,activation='softmax'))

In [23]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [24]:
model.fit(x,y_new,epochs=2000,verbose=1,batch_size=1)

Epoch 1/2000


23/23 [==============================] - 2s 3ms/step - loss: 3.2801 - accuracy: 0.0435
Epoch 2/2000
23/23 [==============================] - 0s 3ms/step - loss: 3.2510 - accuracy: 0.0435
Epoch 3/2000
23/23 [==============================] - 0s 4ms/step - loss: 3.2297 - accuracy: 0.0435
Epoch 4/2000
23/23 [==============================] - 0s 3ms/step - loss: 3.2129 - accuracy: 0.0000e+00
Epoch 5/2000
23/23 [==============================] - 0s 3ms/step - loss: 3.1740 - accuracy: 0.0435
Epoch 6/2000
23/23 [==============================] - 0s 3ms/step - loss: 3.1235 - accuracy: 0.0000e+00
Epoch 7/2000
23/23 [==============================] - 0s 3ms/step - loss: 3.0811 - accuracy: 0.0000e+00
Epoch 8/2000
23/23 [==============================] - 0s 3ms/step - loss: 3.0258 - accuracy: 0.0000e+00
Epoch 9/2000
23/23 [==============================] - 0s 3ms/step - loss: 2.9820 - accuracy: 0.0870
Epoch 10/2000
23/23 [==============================] - 0s 3ms/step - loss: 2.9289 

In [25]:
model.evaluate(x,y_new,batch_size=1)

23/23 [==============================] - 1s 4ms/step - loss: 0.0226 - accuracy: 1.0000


[0.022554948925971985, 1.0]

In [26]:
# Predict

char_new='ABC'

In [29]:
def predict(word):
    val=[char_to_int[char1] for char1 in word]

    val=np.reshape(val,(1,3,1))

    val=val/25

    char_pred=model.predict(val)

    char_pred=np.argmax(char_pred)

    return int_to_char[char_pred]


In [30]:
print(predict(char_new))

1/1 [==============================] - 1s 1s/step
D
