In [1]:
import numpy as np
import tensorflow as tf

In [2]:
alphabets='ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [3]:
len(alphabets)

26

In [4]:
int_to_char=dict(enumerate(alphabets))
int_to_char

{0: 'A',
 1: 'B',
 2: 'C',
 3: 'D',
 4: 'E',
 5: 'F',
 6: 'G',
 7: 'H',
 8: 'I',
 9: 'J',
 10: 'K',
 11: 'L',
 12: 'M',
 13: 'N',
 14: 'O',
 15: 'P',
 16: 'Q',
 17: 'R',
 18: 'S',
 19: 'T',
 20: 'U',
 21: 'V',
 22: 'W',
 23: 'X',
 24: 'Y',
 25: 'Z'}

In [5]:
char_to_int=dict((v,i) for i,v in enumerate(alphabets))
char_to_int

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'J': 9,
 'K': 10,
 'L': 11,
 'M': 12,
 'N': 13,
 'O': 14,
 'P': 15,
 'Q': 16,
 'R': 17,
 'S': 18,
 'T': 19,
 'U': 20,
 'V': 21,
 'W': 22,
 'X': 23,
 'Y': 24,
 'Z': 25}

In [6]:
seq_length=1

In [7]:
x=[]
y=[]
for i in range(len(alphabets)-seq_length):
    seq_in=int_to_char[i]
    seq_out=int_to_char[i+1]
    x+=[[char_to_int[seq_in]]]
    y+=[char_to_int[seq_out]]
    print(seq_in,'->',seq_out)

A -> B
B -> C
C -> D
D -> E
E -> F
F -> G
G -> H
H -> I
I -> J
J -> K
K -> L
L -> M
M -> N
N -> O
O -> P
P -> Q
Q -> R
R -> S
S -> T
T -> U
U -> V
V -> W
W -> X
X -> Y
Y -> Z


In [8]:
x

[[0],
 [1],
 [2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [8],
 [9],
 [10],
 [11],
 [12],
 [13],
 [14],
 [15],
 [16],
 [17],
 [18],
 [19],
 [20],
 [21],
 [22],
 [23],
 [24]]

In [9]:
y

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25]

In [10]:
from tensorflow.keras.utils import to_categorical

In [11]:
y_new=to_categorical(y)

In [12]:
y_new

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

In [13]:
np.array(x).shape

(25, 1)

In [14]:
x=np.reshape(x,(25,1,1))

In [15]:
x

array([[[ 0]],

       [[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]],

       [[12]],

       [[13]],

       [[14]],

       [[15]],

       [[16]],

       [[17]],

       [[18]],

       [[19]],

       [[20]],

       [[21]],

       [[22]],

       [[23]],

       [[24]]])

In [16]:
x=x/25
x

array([[[0.  ]],

       [[0.04]],

       [[0.08]],

       [[0.12]],

       [[0.16]],

       [[0.2 ]],

       [[0.24]],

       [[0.28]],

       [[0.32]],

       [[0.36]],

       [[0.4 ]],

       [[0.44]],

       [[0.48]],

       [[0.52]],

       [[0.56]],

       [[0.6 ]],

       [[0.64]],

       [[0.68]],

       [[0.72]],

       [[0.76]],

       [[0.8 ]],

       [[0.84]],

       [[0.88]],

       [[0.92]],

       [[0.96]]])

#### Building the model

In [17]:
model=tf.keras.models.Sequential([
    tf.keras.layers.Dense(25,activation='relu'),
    tf.keras.layers.LSTM(128),
    tf.keras.layers.Dense(26,activation='softmax')
])

In [18]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [19]:
model.fit(x,y_new,epochs=2000,verbose=1,batch_size=1)

Epoch 1/2000


25/25 [==============================] - 3s 3ms/step - loss: 3.2683 - accuracy: 0.0000e+00
Epoch 2/2000
25/25 [==============================] - 0s 3ms/step - loss: 3.2569 - accuracy: 0.0000e+00
Epoch 3/2000
25/25 [==============================] - 0s 2ms/step - loss: 3.2529 - accuracy: 0.0000e+00
Epoch 4/2000
25/25 [==============================] - 0s 2ms/step - loss: 3.2480 - accuracy: 0.0000e+00
Epoch 5/2000
25/25 [==============================] - 0s 2ms/step - loss: 3.2414 - accuracy: 0.0400
Epoch 6/2000
25/25 [==============================] - 0s 3ms/step - loss: 3.2335 - accuracy: 0.0400
Epoch 7/2000
25/25 [==============================] - 0s 2ms/step - loss: 3.2217 - accuracy: 0.0000e+00
Epoch 8/2000
25/25 [==============================] - 0s 2ms/step - loss: 3.2091 - accuracy: 0.0400
Epoch 9/2000
25/25 [==============================] - 0s 3ms/step - loss: 3.1878 - accuracy: 0.0400
Epoch 10/2000
25/25 [==============================] - 0s 2ms/step - loss: 3.1

In [20]:
model.evaluate(x,y_new,batch_size=1)

25/25 [==============================] - 1s 2ms/step - loss: 0.0996 - accuracy: 1.0000 


[0.09963584691286087, 1.0]

## Prediction on new Data

In [21]:
def predict(alphabet):
    #extract the number
    num=char_to_int[alphabet]

    #reshape the data
    num=np.reshape(num,(1,1,1))

    #normalize
    num=num/25

    #predict
    y_pred=model.predict(num,verbose=False)

    #Find the index of max
    ind=np.argmax(y_pred)

    #extract the alphabet
    print(int_to_char[ind])

In [22]:
predict('E')

F


In [23]:
predict('G')

H
